FROM node:20-alpine As development
RUN apk add g++ make py3-pip
WORKDIR /app
RUN npm install -g firebase-tools 
COPY package.json .
RUN npm install -f
COPY . .
CMD [ "npm run start:dev" ]


FROM node:21-alpine3.18 AS build
WORKDIR /app
COPY package*.json ./
COPY --from=development /app/node_modules ./node_modules
COPY . .
RUN npm run build


