services:
  spc-demo:
    build:
      context: .
      dockerfile: DockerFile.dev
      target: build
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - "4300:2900"
    command: npm run start:dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    container_name: spc-demo
    depends_on:
      - postgres
  pgAdmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"